# Generated by Django 2.1.5 on 2020-01-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(max_length=50)),
                ('app_secret', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WxGroup',
            fields=[
                ('puid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=80)),
                ('avatar', models.URLField()),
            ],
            options={
                'verbose_name': '微信群组',
                'verbose_name_plural': '微信群组',
            },
        ),
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('puid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=80)),
                ('remark_name', models.CharField(max_length=32)),
                ('avatar', models.URLField()),
                ('signature', models.CharField(max_length=255)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('is_friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_friends', to='robot.WxUser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wxuser_owner', to='robot.WxUser')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
        migrations.AddField(
            model_name='wxgroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='robot.WxUser'),
        ),
        migrations.AddField(
            model_name='wxgroup',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxUser'),
        ),
    ]
