# Generated by Django 2.1.5 on 2020-01-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0002_auto_20200104_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='debug_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appmodel',
            name='forward_url',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='app_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='bind_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxUser'),
        ),
    ]
