# Generated by Django 2.1.5 on 2020-01-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0004_auto_20200104_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_name', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=20)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MapMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('scale', models.IntegerField()),
                ('label', models.CharField(max_length=255)),
                ('maptype', models.IntegerField()),
                ('poiname', models.CharField(max_length=255)),
                ('poiid', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Text', '文本'), ('Map', '位置'), ('Card', '名片'), ('Note', '提示'), ('Sharing', '分享'), ('Picture', '图片'), ('Recording', '语音'), ('Attachment', '文件'), ('Video', '视频'), ('Friends', '好友请求'), ('System', '系统')], max_length=15)),
                ('create_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField()),
                ('is_at', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PictureMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_name', models.CharField(max_length=30, verbose_name='文件名')),
                ('url', models.URLField(verbose_name='文件地址')),
                ('img_height', models.IntegerField(verbose_name='图片高度')),
                ('img_width', models.IntegerField(verbose_name='图片宽度')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voice_length', models.BigIntegerField()),
                ('url', models.URLField()),
                ('file_name', models.CharField(max_length=30)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=50)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('text', models.CharField(max_length=2048)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('play_length', models.IntegerField()),
                ('file_name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='avatar',
            field=models.URLField(verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='city',
            field=models.CharField(max_length=15, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='nick_name',
            field=models.CharField(max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='province',
            field=models.CharField(max_length=15, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='remark_name',
            field=models.CharField(max_length=32, verbose_name='备注名'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='signature',
            field=models.CharField(max_length=255, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='user_name',
            field=models.CharField(max_length=80, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='robot.WxUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxGroup'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_user', to='robot.WxUser'),
        ),
        migrations.AddField(
            model_name='mapmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AddField(
            model_name='attachmentmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
    ]
