# Generated by Django 2.1.5 on 2020-01-04 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0005_auto_20200104_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentmessage',
            options={'verbose_name': '文件消息', 'verbose_name_plural': '文件消息'},
        ),
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': '好友请求', 'verbose_name_plural': '好友请求'},
        ),
        migrations.AlterModelOptions(
            name='mapmessage',
            options={'verbose_name': '位置消息', 'verbose_name_plural': '位置消息'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '消息记录', 'verbose_name_plural': '消息记录'},
        ),
        migrations.AlterModelOptions(
            name='picturemessage',
            options={'verbose_name': '图片消息', 'verbose_name_plural': '图片消息'},
        ),
        migrations.AlterModelOptions(
            name='recordingmessage',
            options={'verbose_name': '录音消息', 'verbose_name_plural': '录音消息'},
        ),
        migrations.AlterModelOptions(
            name='sharingmessage',
            options={'verbose_name': '分享消息', 'verbose_name_plural': '分享消息'},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'verbose_name': '文本消息', 'verbose_name_plural': '文本消息'},
        ),
        migrations.AlterModelOptions(
            name='videomessage',
            options={'verbose_name': '视频消息', 'verbose_name_plural': '视频消息'},
        ),
        migrations.AddField(
            model_name='friends',
            name='insert_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='插入时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AddField(
            model_name='friends',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
