# Generated by Django 2.1.5 on 2020-01-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0008_auto_20200105_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='city',
            field=models.CharField(max_length=15, null=True, verbose_name='市'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='nick_name',
            field=models.CharField(max_length=32, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='province',
            field=models.CharField(max_length=15, null=True, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='signature',
            field=models.CharField(max_length=255, null=True, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='user_name',
            field=models.CharField(max_length=80, null=True, verbose_name='用户名'),
        ),
    ]
