# Generated by Django 2.1.5 on 2020-01-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0009_auto_20200105_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodel',
            options={'verbose_name': 'App', 'verbose_name_plural': 'App'},
        ),
        migrations.AddField(
            model_name='wxuser',
            name='friend',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wxgroup',
            name='avatar',
            field=models.URLField(verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='wxgroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='robot.WxUser', verbose_name='群员'),
        ),
        migrations.AlterField(
            model_name='wxgroup',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='wxgroup',
            name='nick_name',
            field=models.CharField(max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='wxgroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxUser', verbose_name='群归属'),
        ),
    ]
