# Generated by Django 2.1.5 on 2020-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0011_auto_20200105_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmessage',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='url',
            field=models.CharField(max_length=50, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='recordingmessage',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sharingmessage',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
