# Generated by Django 2.1.5 on 2020-01-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0012_auto_20200105_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmessage',
            old_name='poiid',
            new_name='puid',
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
