# Generated by Django 2.1.5 on 2020-01-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0013_auto_20200105_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapmessage',
            name='puid',
        ),
        migrations.AddField(
            model_name='mapmessage',
            name='poiid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
