# Generated by Django 2.1.5 on 2020-01-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0014_auto_20200105_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmessage',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='recordingmessage',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
