# Generated by Django 2.1.5 on 2020-01-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0015_auto_20200105_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmessage',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='url',
            field=models.CharField(max_length=500, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='recordingmessage',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sharingmessage',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
