# Generated by Django 2.1.5 on 2020-01-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0016_auto_20200105_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxMps',
            fields=[
                ('insert_time', models.DateTimeField(auto_now_add=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('puid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('nick_name', models.CharField(max_length=32, verbose_name='昵称')),
                ('province', models.CharField(max_length=15, null=True, verbose_name='省')),
                ('city', models.CharField(max_length=15, null=True, verbose_name='市')),
                ('signature', models.CharField(max_length=255, null=True, verbose_name='签名')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxUser', verbose_name='群归属')),
            ],
            options={
                'verbose_name': '微信公众号',
                'verbose_name_plural': '微信公众号',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='maps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.WxMps'),
        ),
    ]
