# Generated by Django 2.1.5 on 2020-01-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0018_auto_20200106_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmessage',
            name='file_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='img_height',
            field=models.IntegerField(null=True, verbose_name='图片高度'),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='img_width',
            field=models.IntegerField(null=True, verbose_name='图片宽度'),
        ),
        migrations.AlterField(
            model_name='recordingmessage',
            name='voice_length',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='play_length',
            field=models.IntegerField(null=True),
        ),
    ]
