# Generated by Django 2.1.5 on 2020-01-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0019_auto_20200106_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='mapmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='picturemessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='recordingmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='sharingmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
        migrations.AlterField(
            model_name='videomessage',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.Message'),
        ),
    ]
