# Generated by Django 2.1.5 on 2020-01-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0022_message_receiver_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodel',
            name='app_name',
            field=models.CharField(default='测试', help_text='app的名称', max_length=20),
            preserve_default=False,
        ),
    ]
